package br.com.demacho.services.usuarioservice.v1;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "UsuarioServiceSOAP", serviceName = "UsuarioService", targetNamespace = "http://demacho.com.br/services/UsuarioService/v1", wsdlLocation = "/wsdls/UsuarioService.wsdl", endpointInterface = "br.com.demacho.services.usuarioservice.v1.UsuarioService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class UsuarioService_UsuarioServiceSOAPImpl implements UsuarioService {

	public UsuarioService_UsuarioServiceSOAPImpl() {
	}

	/**
	 * 
	 * @param usuario
	 * @return returns org.example.demacho.Usuario
	 */
	public org.example.demacho.Usuario buscar(
			br.com.demacho.services.usuarioservice.v1.Usuario usuario) {
		// replace with your impl here
		return null;
	}

}
